using System;
using System.Data;
using System.Data.SqlClient;

namespace XMAdmin
{
	/// <summary>
	/// Provides connectivity and access to the back-end database
	/// that feeds the AMS server
	/// </summary>
	public class Data
	{
		/// <summary>
		/// The connection object. It is preferable to use the
		/// strongly typed functions to access data.
		/// </summary>
		public static SqlConnection Connection = new SqlConnection();

		/// <summary>
		/// Initiate a connection the database. Connection settings
		/// are read on Config.
		/// </summary>
		public static void Connect()
		{
			//ignore if connection is already open
			if (Connection.State == ConnectionState.Open)
				return;

			//open connection
			Connection.ConnectionString = String.Format(
				"Data Source={0};Initial Catalog={1};User ID={2};Password={3};Connect Timeout=4",
				Config.Values[ConfigValues.ServerServer],
				Config.Values[ConfigValues.ServerDatabase],
				Config.Values[ConfigValues.ServerUsername],
				Config.Values[ConfigValues.ServerPassword]);
			Connection.Open();
		}

		/// <summary>
		/// Close the connection to the database.
		/// </summary>
		public static void Disconnect()
		{
			//ignore if connection is already closed
			if (Connection.State == ConnectionState.Closed)
				return;

			//close
			Connection.Close();
		}

		/// <summary>
		/// Executes the given statement on the current connection.
		/// </summary>
		/// <param name="sql">SQL statement to execute.</param>
		/// <returns>Result set generated by the sql statement.</returns>
		public static SqlDataReader Exec(string sql)
		{
			SqlCommand cmd = Connection.CreateCommand();
			cmd.CommandText = sql;
			return cmd.ExecuteReader();
		}

	}
}
