//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLExpress.ShoppingListService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShoppingListItem", Namespace="http://schemas.datacontract.org/2004/07/msn2.net.ShoppingList")]
    [System.SerializableAttribute()]
    public partial class ShoppingListItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ListItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ListItem {
            get {
                return this.ListItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ListItemField, value) != true)) {
                    this.ListItemField = value;
                    this.RaisePropertyChanged("ListItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Store {
            get {
                return this.StoreField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreField, value) != true)) {
                    this.StoreField = value;
                    this.RaisePropertyChanged("Store");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShoppingListService.IShoppingListService")]
    public interface IShoppingListService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingListService/GetStores", ReplyAction="http://tempuri.org/IShoppingListService/GetStoresResponse")]
        System.Collections.Generic.List<string> GetStores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingListService/GetShoppingListItems", ReplyAction="http://tempuri.org/IShoppingListService/GetShoppingListItemsResponse")]
        System.Collections.Generic.List<SLExpress.ShoppingListService.ShoppingListItem> GetShoppingListItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingListService/GetShoppingListItemsForStore", ReplyAction="http://tempuri.org/IShoppingListService/GetShoppingListItemsForStoreResponse")]
        System.Collections.Generic.List<SLExpress.ShoppingListService.ShoppingListItem> GetShoppingListItemsForStore(string store);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingListService/AddShoppingListItem", ReplyAction="http://tempuri.org/IShoppingListService/AddShoppingListItemResponse")]
        SLExpress.ShoppingListService.ShoppingListItem AddShoppingListItem(string store, string listItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingListService/DeleteShoppingListItem", ReplyAction="http://tempuri.org/IShoppingListService/DeleteShoppingListItemResponse")]
        void DeleteShoppingListItem(SLExpress.ShoppingListService.ShoppingListItem listItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingListService/UpdateShoppingListItem", ReplyAction="http://tempuri.org/IShoppingListService/UpdateShoppingListItemResponse")]
        void UpdateShoppingListItem(SLExpress.ShoppingListService.ShoppingListItem listItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingListService/GetMobileClientVersion", ReplyAction="http://tempuri.org/IShoppingListService/GetMobileClientVersionResponse")]
        string GetMobileClientVersion();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShoppingListServiceChannel : SLExpress.ShoppingListService.IShoppingListService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShoppingListServiceClient : System.ServiceModel.ClientBase<SLExpress.ShoppingListService.IShoppingListService>, SLExpress.ShoppingListService.IShoppingListService {
        
        public ShoppingListServiceClient() {
        }
        
        public ShoppingListServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShoppingListServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShoppingListServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShoppingListServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<string> GetStores() {
            return base.Channel.GetStores();
        }
        
        public System.Collections.Generic.List<SLExpress.ShoppingListService.ShoppingListItem> GetShoppingListItems() {
            return base.Channel.GetShoppingListItems();
        }
        
        public System.Collections.Generic.List<SLExpress.ShoppingListService.ShoppingListItem> GetShoppingListItemsForStore(string store) {
            return base.Channel.GetShoppingListItemsForStore(store);
        }
        
        public SLExpress.ShoppingListService.ShoppingListItem AddShoppingListItem(string store, string listItem) {
            return base.Channel.AddShoppingListItem(store, listItem);
        }
        
        public void DeleteShoppingListItem(SLExpress.ShoppingListService.ShoppingListItem listItem) {
            base.Channel.DeleteShoppingListItem(listItem);
        }
        
        public void UpdateShoppingListItem(SLExpress.ShoppingListService.ShoppingListItem listItem) {
            base.Channel.UpdateShoppingListItem(listItem);
        }
        
        public string GetMobileClientVersion() {
            return base.Channel.GetMobileClientVersion();
        }
    }
}
