//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3328.4
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace PicAdminCS {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class DataSetPerson : DataSet {
        
        private PersonDataTable tablePerson;
        
        private PersonGroupDataTable tablePersonGroup;
        
        private DataRelation relationPersonPersonGroup;
        
        public DataSetPerson() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected DataSetPerson(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Person"] != null)) {
                    this.Tables.Add(new PersonDataTable(ds.Tables["Person"]));
                }
                if ((ds.Tables["PersonGroup"] != null)) {
                    this.Tables.Add(new PersonGroupDataTable(ds.Tables["PersonGroup"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public PersonDataTable Person {
            get {
                return this.tablePerson;
            }
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public PersonGroupDataTable PersonGroup {
            get {
                return this.tablePersonGroup;
            }
        }
        
        public override DataSet Clone() {
            DataSetPerson cln = ((DataSetPerson)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["Person"] != null)) {
                this.Tables.Add(new PersonDataTable(ds.Tables["Person"]));
            }
            if ((ds.Tables["PersonGroup"] != null)) {
                this.Tables.Add(new PersonGroupDataTable(ds.Tables["PersonGroup"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tablePerson = ((PersonDataTable)(this.Tables["Person"]));
            if ((this.tablePerson != null)) {
                this.tablePerson.InitVars();
            }
            this.tablePersonGroup = ((PersonGroupDataTable)(this.Tables["PersonGroup"]));
            if ((this.tablePersonGroup != null)) {
                this.tablePersonGroup.InitVars();
            }
            this.relationPersonPersonGroup = this.Relations["PersonPersonGroup"];
        }
        
        private void InitClass() {
            this.DataSetName = "DataSetPerson";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DataSetPerson.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tablePerson = new PersonDataTable();
            this.Tables.Add(this.tablePerson);
            this.tablePersonGroup = new PersonGroupDataTable();
            this.Tables.Add(this.tablePersonGroup);
            ForeignKeyConstraint fkc;
            fkc = new ForeignKeyConstraint("PersonPersonGroup", new DataColumn[] {
                        this.tablePerson.PersonIDColumn}, new DataColumn[] {
                        this.tablePersonGroup.PersonIDColumn});
            this.tablePersonGroup.Constraints.Add(fkc);
            fkc.AcceptRejectRule = AcceptRejectRule.None;
            fkc.DeleteRule = Rule.Cascade;
            fkc.UpdateRule = Rule.Cascade;
            this.relationPersonPersonGroup = new DataRelation("PersonPersonGroup", new DataColumn[] {
                        this.tablePerson.PersonIDColumn}, new DataColumn[] {
                        this.tablePersonGroup.PersonIDColumn}, false);
            this.Relations.Add(this.relationPersonPersonGroup);
        }
        
        private bool ShouldSerializePerson() {
            return false;
        }
        
        private bool ShouldSerializePersonGroup() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void PersonRowChangeEventHandler(object sender, PersonRowChangeEvent e);
        
        public delegate void PersonGroupRowChangeEventHandler(object sender, PersonGroupRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class PersonDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnPersonID;
            
            private DataColumn columnLastName;
            
            private DataColumn columnFirstName;
            
            private DataColumn columnFullName;
            
            private DataColumn columnEmail;
            
            private DataColumn columnPassword;
            
            private DataColumn columnResetPWGuid;
            
            private DataColumn columnResetPWExpire;
            
            internal PersonDataTable() : 
                    base("Person") {
                this.InitClass();
            }
            
            internal PersonDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn PersonIDColumn {
                get {
                    return this.columnPersonID;
                }
            }
            
            internal DataColumn LastNameColumn {
                get {
                    return this.columnLastName;
                }
            }
            
            internal DataColumn FirstNameColumn {
                get {
                    return this.columnFirstName;
                }
            }
            
            internal DataColumn FullNameColumn {
                get {
                    return this.columnFullName;
                }
            }
            
            internal DataColumn EmailColumn {
                get {
                    return this.columnEmail;
                }
            }
            
            internal DataColumn PasswordColumn {
                get {
                    return this.columnPassword;
                }
            }
            
            internal DataColumn ResetPWGuidColumn {
                get {
                    return this.columnResetPWGuid;
                }
            }
            
            internal DataColumn ResetPWExpireColumn {
                get {
                    return this.columnResetPWExpire;
                }
            }
            
            public PersonRow this[int index] {
                get {
                    return ((PersonRow)(this.Rows[index]));
                }
            }
            
            public event PersonRowChangeEventHandler PersonRowChanged;
            
            public event PersonRowChangeEventHandler PersonRowChanging;
            
            public event PersonRowChangeEventHandler PersonRowDeleted;
            
            public event PersonRowChangeEventHandler PersonRowDeleting;
            
            public void AddPersonRow(PersonRow row) {
                this.Rows.Add(row);
            }
            
            public PersonRow AddPersonRow(string LastName, string FirstName, string FullName, string Email, string Password, System.Byte[] ResetPWGuid, System.DateTime ResetPWExpire) {
                PersonRow rowPersonRow = ((PersonRow)(this.NewRow()));
                rowPersonRow.ItemArray = new object[] {
                        null,
                        LastName,
                        FirstName,
                        FullName,
                        Email,
                        Password,
                        ResetPWGuid,
                        ResetPWExpire};
                this.Rows.Add(rowPersonRow);
                return rowPersonRow;
            }
            
            public PersonRow FindByPersonID(int PersonID) {
                return ((PersonRow)(this.Rows.Find(new object[] {
                            PersonID})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                PersonDataTable cln = ((PersonDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            internal void InitVars() {
                this.columnPersonID = this.Columns["PersonID"];
                this.columnLastName = this.Columns["LastName"];
                this.columnFirstName = this.Columns["FirstName"];
                this.columnFullName = this.Columns["FullName"];
                this.columnEmail = this.Columns["Email"];
                this.columnPassword = this.Columns["Password"];
                this.columnResetPWGuid = this.Columns["ResetPWGuid"];
                this.columnResetPWExpire = this.Columns["ResetPWExpire"];
            }
            
            private void InitClass() {
                this.columnPersonID = new DataColumn("PersonID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPersonID);
                this.columnLastName = new DataColumn("LastName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnLastName);
                this.columnFirstName = new DataColumn("FirstName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFirstName);
                this.columnFullName = new DataColumn("FullName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnFullName);
                this.columnEmail = new DataColumn("Email", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnEmail);
                this.columnPassword = new DataColumn("Password", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPassword);
                this.columnResetPWGuid = new DataColumn("ResetPWGuid", typeof(System.Byte[]), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnResetPWGuid);
                this.columnResetPWExpire = new DataColumn("ResetPWExpire", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnResetPWExpire);
                this.Constraints.Add(new UniqueConstraint("DataSetPersonKey1", new DataColumn[] {
                                this.columnPersonID}, true));
                this.columnPersonID.AutoIncrement = true;
                this.columnPersonID.AllowDBNull = false;
                this.columnPersonID.ReadOnly = true;
                this.columnPersonID.Unique = true;
            }
            
            public PersonRow NewPersonRow() {
                return ((PersonRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new PersonRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(PersonRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.PersonRowChanged != null)) {
                    this.PersonRowChanged(this, new PersonRowChangeEvent(((PersonRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.PersonRowChanging != null)) {
                    this.PersonRowChanging(this, new PersonRowChangeEvent(((PersonRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.PersonRowDeleted != null)) {
                    this.PersonRowDeleted(this, new PersonRowChangeEvent(((PersonRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.PersonRowDeleting != null)) {
                    this.PersonRowDeleting(this, new PersonRowChangeEvent(((PersonRow)(e.Row)), e.Action));
                }
            }
            
            public void RemovePersonRow(PersonRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class PersonRow : DataRow {
            
            private PersonDataTable tablePerson;
            
            internal PersonRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tablePerson = ((PersonDataTable)(this.Table));
            }
            
            public int PersonID {
                get {
                    return ((int)(this[this.tablePerson.PersonIDColumn]));
                }
                set {
                    this[this.tablePerson.PersonIDColumn] = value;
                }
            }
            
            public string LastName {
                get {
                    try {
                        return ((string)(this[this.tablePerson.LastNameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePerson.LastNameColumn] = value;
                }
            }
            
            public string FirstName {
                get {
                    try {
                        return ((string)(this[this.tablePerson.FirstNameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePerson.FirstNameColumn] = value;
                }
            }
            
            public string FullName {
                get {
                    try {
                        return ((string)(this[this.tablePerson.FullNameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePerson.FullNameColumn] = value;
                }
            }
            
            public string Email {
                get {
                    try {
                        return ((string)(this[this.tablePerson.EmailColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePerson.EmailColumn] = value;
                }
            }
            
            public string Password {
                get {
                    try {
                        return ((string)(this[this.tablePerson.PasswordColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePerson.PasswordColumn] = value;
                }
            }
            
            public System.Byte[] ResetPWGuid {
                get {
                    try {
                        return ((System.Byte[])(this[this.tablePerson.ResetPWGuidColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePerson.ResetPWGuidColumn] = value;
                }
            }
            
            public System.DateTime ResetPWExpire {
                get {
                    try {
                        return ((System.DateTime)(this[this.tablePerson.ResetPWExpireColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePerson.ResetPWExpireColumn] = value;
                }
            }
            
            public bool IsLastNameNull() {
                return this.IsNull(this.tablePerson.LastNameColumn);
            }
            
            public void SetLastNameNull() {
                this[this.tablePerson.LastNameColumn] = System.Convert.DBNull;
            }
            
            public bool IsFirstNameNull() {
                return this.IsNull(this.tablePerson.FirstNameColumn);
            }
            
            public void SetFirstNameNull() {
                this[this.tablePerson.FirstNameColumn] = System.Convert.DBNull;
            }
            
            public bool IsFullNameNull() {
                return this.IsNull(this.tablePerson.FullNameColumn);
            }
            
            public void SetFullNameNull() {
                this[this.tablePerson.FullNameColumn] = System.Convert.DBNull;
            }
            
            public bool IsEmailNull() {
                return this.IsNull(this.tablePerson.EmailColumn);
            }
            
            public void SetEmailNull() {
                this[this.tablePerson.EmailColumn] = System.Convert.DBNull;
            }
            
            public bool IsPasswordNull() {
                return this.IsNull(this.tablePerson.PasswordColumn);
            }
            
            public void SetPasswordNull() {
                this[this.tablePerson.PasswordColumn] = System.Convert.DBNull;
            }
            
            public bool IsResetPWGuidNull() {
                return this.IsNull(this.tablePerson.ResetPWGuidColumn);
            }
            
            public void SetResetPWGuidNull() {
                this[this.tablePerson.ResetPWGuidColumn] = System.Convert.DBNull;
            }
            
            public bool IsResetPWExpireNull() {
                return this.IsNull(this.tablePerson.ResetPWExpireColumn);
            }
            
            public void SetResetPWExpireNull() {
                this[this.tablePerson.ResetPWExpireColumn] = System.Convert.DBNull;
            }
            
            public PersonGroupRow[] GetPersonGroupRows() {
                return ((PersonGroupRow[])(this.GetChildRows(this.Table.ChildRelations["PersonPersonGroup"])));
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class PersonRowChangeEvent : EventArgs {
            
            private PersonRow eventRow;
            
            private DataRowAction eventAction;
            
            public PersonRowChangeEvent(PersonRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public PersonRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class PersonGroupDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnPersonGroupID;
            
            private DataColumn columnPersonID;
            
            private DataColumn columnGroupID;
            
            internal PersonGroupDataTable() : 
                    base("PersonGroup") {
                this.InitClass();
            }
            
            internal PersonGroupDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn PersonGroupIDColumn {
                get {
                    return this.columnPersonGroupID;
                }
            }
            
            internal DataColumn PersonIDColumn {
                get {
                    return this.columnPersonID;
                }
            }
            
            internal DataColumn GroupIDColumn {
                get {
                    return this.columnGroupID;
                }
            }
            
            public PersonGroupRow this[int index] {
                get {
                    return ((PersonGroupRow)(this.Rows[index]));
                }
            }
            
            public event PersonGroupRowChangeEventHandler PersonGroupRowChanged;
            
            public event PersonGroupRowChangeEventHandler PersonGroupRowChanging;
            
            public event PersonGroupRowChangeEventHandler PersonGroupRowDeleted;
            
            public event PersonGroupRowChangeEventHandler PersonGroupRowDeleting;
            
            public void AddPersonGroupRow(PersonGroupRow row) {
                this.Rows.Add(row);
            }
            
            public PersonGroupRow AddPersonGroupRow(PersonRow parentPersonRowByPersonPersonGroup, int GroupID) {
                PersonGroupRow rowPersonGroupRow = ((PersonGroupRow)(this.NewRow()));
                rowPersonGroupRow.ItemArray = new object[] {
                        null,
                        parentPersonRowByPersonPersonGroup[0],
                        GroupID};
                this.Rows.Add(rowPersonGroupRow);
                return rowPersonGroupRow;
            }
            
            public PersonGroupRow FindByPersonIDGroupID(int PersonID, int GroupID) {
                return ((PersonGroupRow)(this.Rows.Find(new object[] {
                            PersonID,
                            GroupID})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                PersonGroupDataTable cln = ((PersonGroupDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            internal void InitVars() {
                this.columnPersonGroupID = this.Columns["PersonGroupID"];
                this.columnPersonID = this.Columns["PersonID"];
                this.columnGroupID = this.Columns["GroupID"];
            }
            
            private void InitClass() {
                this.columnPersonGroupID = new DataColumn("PersonGroupID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPersonGroupID);
                this.columnPersonID = new DataColumn("PersonID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPersonID);
                this.columnGroupID = new DataColumn("GroupID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnGroupID);
                this.Constraints.Add(new UniqueConstraint("DataSetPersonKey2", new DataColumn[] {
                                this.columnPersonID,
                                this.columnGroupID}, true));
                this.columnPersonGroupID.AutoIncrement = true;
                this.columnPersonGroupID.AllowDBNull = false;
                this.columnPersonGroupID.ReadOnly = true;
                this.columnPersonID.AllowDBNull = false;
                this.columnGroupID.AllowDBNull = false;
            }
            
            public PersonGroupRow NewPersonGroupRow() {
                return ((PersonGroupRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new PersonGroupRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(PersonGroupRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.PersonGroupRowChanged != null)) {
                    this.PersonGroupRowChanged(this, new PersonGroupRowChangeEvent(((PersonGroupRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.PersonGroupRowChanging != null)) {
                    this.PersonGroupRowChanging(this, new PersonGroupRowChangeEvent(((PersonGroupRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.PersonGroupRowDeleted != null)) {
                    this.PersonGroupRowDeleted(this, new PersonGroupRowChangeEvent(((PersonGroupRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.PersonGroupRowDeleting != null)) {
                    this.PersonGroupRowDeleting(this, new PersonGroupRowChangeEvent(((PersonGroupRow)(e.Row)), e.Action));
                }
            }
            
            public void RemovePersonGroupRow(PersonGroupRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class PersonGroupRow : DataRow {
            
            private PersonGroupDataTable tablePersonGroup;
            
            internal PersonGroupRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tablePersonGroup = ((PersonGroupDataTable)(this.Table));
            }
            
            public int PersonGroupID {
                get {
                    return ((int)(this[this.tablePersonGroup.PersonGroupIDColumn]));
                }
                set {
                    this[this.tablePersonGroup.PersonGroupIDColumn] = value;
                }
            }
            
            public int PersonID {
                get {
                    return ((int)(this[this.tablePersonGroup.PersonIDColumn]));
                }
                set {
                    this[this.tablePersonGroup.PersonIDColumn] = value;
                }
            }
            
            public int GroupID {
                get {
                    return ((int)(this[this.tablePersonGroup.GroupIDColumn]));
                }
                set {
                    this[this.tablePersonGroup.GroupIDColumn] = value;
                }
            }
            
            public PersonRow PersonRow {
                get {
                    return ((PersonRow)(this.GetParentRow(this.Table.ParentRelations["PersonPersonGroup"])));
                }
                set {
                    this.SetParentRow(value, this.Table.ParentRelations["PersonPersonGroup"]);
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class PersonGroupRowChangeEvent : EventArgs {
            
            private PersonGroupRow eventRow;
            
            private DataRowAction eventAction;
            
            public PersonGroupRowChangeEvent(PersonGroupRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public PersonGroupRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
