//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarMonkeyTest.BarMonkeyClientService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Drink", Namespace="http://schemas.datacontract.org/2004/07/msn2.net.BarMonkey")]
    [System.SerializableAttribute()]
    public partial class Drink : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPublishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<BarMonkeyTest.BarMonkeyClientService.UserFavorite> UserFavoritesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<BarMonkeyTest.BarMonkeyClientService.DrinkIngredient> DrinkIngredientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<BarMonkeyTest.BarMonkeyClientService.UserDrinkHistory> UserDrinkHistoriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool IsPublished {
            get {
                return this.IsPublishedField;
            }
            set {
                if ((this.IsPublishedField.Equals(value) != true)) {
                    this.IsPublishedField = value;
                    this.RaisePropertyChanged("IsPublished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public System.Collections.Generic.List<BarMonkeyTest.BarMonkeyClientService.UserFavorite> UserFavorites {
            get {
                return this.UserFavoritesField;
            }
            set {
                if ((object.ReferenceEquals(this.UserFavoritesField, value) != true)) {
                    this.UserFavoritesField = value;
                    this.RaisePropertyChanged("UserFavorites");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public System.Collections.Generic.List<BarMonkeyTest.BarMonkeyClientService.DrinkIngredient> DrinkIngredients {
            get {
                return this.DrinkIngredientsField;
            }
            set {
                if ((object.ReferenceEquals(this.DrinkIngredientsField, value) != true)) {
                    this.DrinkIngredientsField = value;
                    this.RaisePropertyChanged("DrinkIngredients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public System.Collections.Generic.List<BarMonkeyTest.BarMonkeyClientService.UserDrinkHistory> UserDrinkHistories {
            get {
                return this.UserDrinkHistoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDrinkHistoriesField, value) != true)) {
                    this.UserDrinkHistoriesField = value;
                    this.RaisePropertyChanged("UserDrinkHistories");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserFavorite", Namespace="http://schemas.datacontract.org/2004/07/msn2.net.BarMonkey")]
    [System.SerializableAttribute()]
    public partial class UserFavorite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DrinkIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int DrinkId {
            get {
                return this.DrinkIdField;
            }
            set {
                if ((this.DrinkIdField.Equals(value) != true)) {
                    this.DrinkIdField = value;
                    this.RaisePropertyChanged("DrinkId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DrinkIngredient", Namespace="http://schemas.datacontract.org/2004/07/msn2.net.BarMonkey")]
    [System.SerializableAttribute()]
    public partial class DrinkIngredient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DrinkIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IngredientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SequenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountOuncesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int DrinkId {
            get {
                return this.DrinkIdField;
            }
            set {
                if ((this.DrinkIdField.Equals(value) != true)) {
                    this.DrinkIdField = value;
                    this.RaisePropertyChanged("DrinkId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int IngredientId {
            get {
                return this.IngredientIdField;
            }
            set {
                if ((this.IngredientIdField.Equals(value) != true)) {
                    this.IngredientIdField = value;
                    this.RaisePropertyChanged("IngredientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Sequence {
            get {
                return this.SequenceField;
            }
            set {
                if ((this.SequenceField.Equals(value) != true)) {
                    this.SequenceField = value;
                    this.RaisePropertyChanged("Sequence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Group {
            get {
                return this.GroupField;
            }
            set {
                if ((this.GroupField.Equals(value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal AmountOunces {
            get {
                return this.AmountOuncesField;
            }
            set {
                if ((this.AmountOuncesField.Equals(value) != true)) {
                    this.AmountOuncesField = value;
                    this.RaisePropertyChanged("AmountOunces");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDrinkHistory", Namespace="http://schemas.datacontract.org/2004/07/msn2.net.BarMonkey")]
    [System.SerializableAttribute()]
    public partial class UserDrinkHistory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DrinkIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<BarMonkeyTest.BarMonkeyClientService.UserDrinkIngredientHistory> UserDrinkIngredientHistoriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int DrinkId {
            get {
                return this.DrinkIdField;
            }
            set {
                if ((this.DrinkIdField.Equals(value) != true)) {
                    this.DrinkIdField = value;
                    this.RaisePropertyChanged("DrinkId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public System.Collections.Generic.List<BarMonkeyTest.BarMonkeyClientService.UserDrinkIngredientHistory> UserDrinkIngredientHistories {
            get {
                return this.UserDrinkIngredientHistoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDrinkIngredientHistoriesField, value) != true)) {
                    this.UserDrinkIngredientHistoriesField = value;
                    this.RaisePropertyChanged("UserDrinkIngredientHistories");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDrinkIngredientHistory", Namespace="http://schemas.datacontract.org/2004/07/msn2.net.BarMonkey")]
    [System.SerializableAttribute()]
    public partial class UserDrinkIngredientHistory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserDrinkHistoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IngredientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountOuncesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SequenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserDrinkHistoryId {
            get {
                return this.UserDrinkHistoryIdField;
            }
            set {
                if ((this.UserDrinkHistoryIdField.Equals(value) != true)) {
                    this.UserDrinkHistoryIdField = value;
                    this.RaisePropertyChanged("UserDrinkHistoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int IngredientId {
            get {
                return this.IngredientIdField;
            }
            set {
                if ((this.IngredientIdField.Equals(value) != true)) {
                    this.IngredientIdField = value;
                    this.RaisePropertyChanged("IngredientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal AmountOunces {
            get {
                return this.AmountOuncesField;
            }
            set {
                if ((this.AmountOuncesField.Equals(value) != true)) {
                    this.AmountOuncesField = value;
                    this.RaisePropertyChanged("AmountOunces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Sequence {
            get {
                return this.SequenceField;
            }
            set {
                if ((this.SequenceField.Equals(value) != true)) {
                    this.SequenceField = value;
                    this.RaisePropertyChanged("Sequence");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BarMonkeyClientService.IBarMonkeyClientService")]
    public interface IBarMonkeyClientService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBarMonkeyClientService/GetTopDrinks", ReplyAction="http://tempuri.org/IBarMonkeyClientService/GetTopDrinksResponse")]
        System.Collections.Generic.List<BarMonkeyTest.BarMonkeyClientService.Drink> GetTopDrinks(int count);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBarMonkeyClientService/GetTopDrinks", ReplyAction="http://tempuri.org/IBarMonkeyClientService/GetTopDrinksResponse")]
        System.IAsyncResult BeginGetTopDrinks(int count, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<BarMonkeyTest.BarMonkeyClientService.Drink> EndGetTopDrinks(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBarMonkeyClientServiceChannel : BarMonkeyTest.BarMonkeyClientService.IBarMonkeyClientService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTopDrinksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTopDrinksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<BarMonkeyTest.BarMonkeyClientService.Drink> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<BarMonkeyTest.BarMonkeyClientService.Drink>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BarMonkeyClientServiceClient : System.ServiceModel.ClientBase<BarMonkeyTest.BarMonkeyClientService.IBarMonkeyClientService>, BarMonkeyTest.BarMonkeyClientService.IBarMonkeyClientService {
        
        private BeginOperationDelegate onBeginGetTopDrinksDelegate;
        
        private EndOperationDelegate onEndGetTopDrinksDelegate;
        
        private System.Threading.SendOrPostCallback onGetTopDrinksCompletedDelegate;
        
        public BarMonkeyClientServiceClient() {
        }
        
        public BarMonkeyClientServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BarMonkeyClientServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BarMonkeyClientServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BarMonkeyClientServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetTopDrinksCompletedEventArgs> GetTopDrinksCompleted;
        
        public System.Collections.Generic.List<BarMonkeyTest.BarMonkeyClientService.Drink> GetTopDrinks(int count) {
            return base.Channel.GetTopDrinks(count);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetTopDrinks(int count, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTopDrinks(count, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<BarMonkeyTest.BarMonkeyClientService.Drink> EndGetTopDrinks(System.IAsyncResult result) {
            return base.Channel.EndGetTopDrinks(result);
        }
        
        private System.IAsyncResult OnBeginGetTopDrinks(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int count = ((int)(inValues[0]));
            return this.BeginGetTopDrinks(count, callback, asyncState);
        }
        
        private object[] OnEndGetTopDrinks(System.IAsyncResult result) {
            System.Collections.Generic.List<BarMonkeyTest.BarMonkeyClientService.Drink> retVal = this.EndGetTopDrinks(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTopDrinksCompleted(object state) {
            if ((this.GetTopDrinksCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTopDrinksCompleted(this, new GetTopDrinksCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTopDrinksAsync(int count) {
            this.GetTopDrinksAsync(count, null);
        }
        
        public void GetTopDrinksAsync(int count, object userState) {
            if ((this.onBeginGetTopDrinksDelegate == null)) {
                this.onBeginGetTopDrinksDelegate = new BeginOperationDelegate(this.OnBeginGetTopDrinks);
            }
            if ((this.onEndGetTopDrinksDelegate == null)) {
                this.onEndGetTopDrinksDelegate = new EndOperationDelegate(this.OnEndGetTopDrinks);
            }
            if ((this.onGetTopDrinksCompletedDelegate == null)) {
                this.onGetTopDrinksCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTopDrinksCompleted);
            }
            base.InvokeAsync(this.onBeginGetTopDrinksDelegate, new object[] {
                        count}, this.onEndGetTopDrinksDelegate, this.onGetTopDrinksCompletedDelegate, userState);
        }
    }
}
