<?xml version="1.0" encoding="utf-8"?>
<Database Name="ShoppingList" Class="SLSDataDataContext" AccessModifier="Internal" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=stan;Initial Catalog=ShoppingList;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ShoppingListConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Store" Member="Stores">
    <Type Name="Store">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Store_StoreItem" Member="StoreItems" OtherKey="StoreId" Type="StoreItem" />
    </Type>
  </Table>
  <Table Name="dbo.StoreItem" Member="StoreItems">
    <Type Name="StoreItem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StoreId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" />
      <Association Name="Store_StoreItem" Member="Store" ThisKey="StoreId" Type="Store" IsForeignKey="true" />
    </Type>
  </Table>
</Database>