//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by XMClient.rc
//
#define IDC_ADD                         3
#define IDC_CLEAR                       3
#define IDC_REMOVE                      4
#define IDC_INDEX                       6
#define IDC_DOWNLOAD                    7
#define IDD_ABOUTBOX                    100
#define IDC_CREATESESSION               101
#define IDC_SESSIONLIST                 102
#define IDC_SENDMESSAGE                 103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDC_TIMERMESSAGE                104
#define IDC_LISTEN                      105
#define IDC_PIC                         106
#define IDD_PREFS_GENERAL               106
#define IDD_INDEX_CAT                   107
#define IDC_DBDIALOG                    108
#define IDC_SPLITTER                    109
#define IDC_TABS                        110
#define IDC_LOGO                        111
#define IDC_BANNER                      112
#define IDC_NETMON                      113
#define IDC_SEARCH_TOOLS                114
#define IDC_SEARCH_SAVEDTOOLS           115
#define IDC_SEARCH_SAVEDFRAME           116
#define IDC_SEARCH_SAVEDLIST            117
#define IDC_SEARCH_THUMBS               118
#define ID_SEARCH_SEARCH                119
#define ID_SEARCH_EDIT                  120
#define ID_SEARCH_SAVE                  121
#define ID_SEARCH_SAVEDSEARCH           122
#define ID_SEARCH_SAVEDEDIT             123
#define ID_SEARCH_SAVEDDELETE           124
#define IDC_SAVE                        125
#define IDC_SHRINK                      126
#define ID_SHRINK                       127
#define IDR_MAINFRAME                   128
#define IDC_ADVERT                      128
#define IDR_XMClientTYPE                129
#define IDD_DB                          132
#define IDD_LOGIN                       134
#define IDD_INDEX_PICTURE               136
#define IDD_INDEX_PHYSGEN               137
#define IDD_INDEX_PHYSSPEC              138
#define IDD_INDEX_FEMALE                139
#define IDD_INDEX_MALE                  140
#define IDD_INDEX_CAT2                  141
#define IDD_QUERY                       142
#define IDD_QUERYTEST                   143
#define IDD_PREFS_SEARCHING             144
#define IDB_LOGO_170                    145
#define IDD_PREFS_DOWNLOADING           145
#define IDC_VSPLIT                      146
#define IDD_PREFS_UPLOADING             146
#define IDD_PREFS_ADVANCED              147
#define IDB_SEARCHTOOLS                 151
#define IDB_LOGO_80                     152
#define IDB_THUMBNAIL_DOWNLOADING       156
#define IDB_THUMBNAIL_ERROR             157
#define IDB_THUMBNAIL_WAITING           158
#define IDB_TABS                        159
#define IDR_IMAGE                       160
#define IDC_HANDOPEN                    161
#define IDC_HANDCLOSED                  162
#define IDR_THUMBNAIL                   164
#define IDD_CHANGEPWD                   165
#define IDR_INDEXER                     167
#define IDD_INDEXER_CHANGEFIELD         168
#define IDD_INDEXER_LISTING             169
#define IDD_INDEXER_JUMPTO              170
#define IDR_LOGO                        171
#define IDB_SHRINKLEFT                  172
#define IDB_SHRINKDOWN                  173
#define IDD_PWD                         174
#define IDD_ABOUT                       175
#define IDD_SHARED                      176
#define IDR_LOCAL                       178
#define IDD_SAVESEARCH                  179
#define IDD_AU                          182
#define IDD_RECONNECT                   183
#define IDC_FILES                       1000
#define IDC_PICSIZE                     1001
#define IDC_DBPATH                      1002
#define IDC_SCAN                        1003
#define IDC_PATH2                       1004
#define IDC_DBLOAD                      1005
#define IDC_DBSAVE                      1006
#define IDC_LOG                         1007
#define IDC_LOGIN                       1008
#define IDC_PASSWORD                    1009
#define IDC_LOGINBUTTON                 1010
#define IDC_EDIT1                       1011
#define IDC_STATUS                      1011
#define IDC_MINWIDTH                    1011
#define IDC_USERNAME                    1011
#define IDC_LASTN                       1011
#define IDC_CONFIG                      1011
#define IDC_PWD_OLD                     1011
#define IDC_MINHEIGHT                   1012
#define IDC_DB                          1012
#define IDC_PWD_NEW                     1012
#define IDC_SETTING1                    1013
#define IDC_MINSIZE                     1013
#define IDC_PWD_VERIFY                  1013
#define IDC_SETTING2                    1014
#define IDC_SETTING3                    1015
#define IDC_SETTING4                    1016
#define IDC_SETTING5                    1017
#define IDC_RATING1                     1018
#define IDC_RATING2                     1019
#define IDC_RATING3                     1020
#define IDC_RATING4                     1021
#define IDC_RATING5                     1022
#define IDC_RATING6                     1023
#define IDC_GENDER1                     1024
#define IDC_GENDER2                     1025
#define IDC_GENDER3                     1026
#define IDC_GENDER4                     1027
#define IDC_QUALITY1                    1028
#define IDC_QUALITY2                    1029
#define IDC_QUALITY3                    1030
#define IDC_SKIN4                       1031
#define IDC_QUANTITY1                   1032
#define IDC_QUANTITY2                   1033
#define IDC_QUANTITY3                   1034
#define IDC_QUANTITY4                   1035
#define IDC_QUANTITY5                   1036
#define IDC_QUANTITY6                   1037
#define IDC_BUTT3                       1038
#define IDC_BUTT4                       1039
#define IDC_BUTT5                       1040
#define IDC_BUTT6                       1041
#define IDC_BUTT7                       1042
#define IDC_BUTT8                       1043
#define IDC_CAT1                        1044
#define IDC_LEGS1                       1044
#define IDC_CAT2                        1045
#define IDC_LEGS2                       1045
#define IDC_CAT3                        1046
#define IDC_LEGS3                       1046
#define IDC_CAT4                        1047
#define IDC_LEGS4                       1047
#define IDC_CAT5                        1048
#define IDC_LEGS5                       1048
#define IDC_CAT6                        1049
#define IDC_LEGS6                       1049
#define IDC_CAT7                        1050
#define IDC_LEGS7                       1050
#define IDC_CAT8                        1051
#define IDC_LEGS8                       1051
#define IDC_CAT9                        1052
#define IDC_CAT10                       1053
#define IDC_CAT11                       1054
#define IDC_CAT12                       1055
#define IDC_CAT13                       1056
#define IDC_CAT14                       1057
#define IDC_CAT15                       1058
#define IDC_CAT16                       1059
#define IDC_CAT17                       1060
#define IDC_CAT18                       1061
#define IDC_CAT19                       1062
#define IDC_CAT20                       1063
#define IDC_CAT21                       1064
#define IDC_CAT22                       1065
#define IDC_CAT23                       1066
#define IDC_CAT24                       1067
#define IDC_CAT25                       1068
#define IDC_CAT26                       1069
#define IDC_CAT27                       1070
#define IDC_CAT28                       1071
#define IDC_CAT29                       1072
#define IDC_CAT30                       1073
#define IDC_CAT31                       1074
#define IDC_NIPPLES1                    1075
#define IDC_NIPPLES2                    1076
#define IDC_NIPPLES3                    1077
#define IDC_NIPPLES4                    1078
#define IDC_NIPPLES5                    1079
#define IDC_HIPS1                       1080
#define IDC_HIPS2                       1081
#define IDC_HIPS3                       1082
#define IDC_HIPS4                       1083
#define IDC_BREASTS1                    1084
#define IDC_BREASTS2                    1085
#define IDC_BREASTS3                    1086
#define IDC_BREASTS4                    1087
#define IDC_BREASTS5                    1088
#define IDC_BREASTS6                    1089
#define IDC_FEMGEN1                     1090
#define IDC_FEMGEN2                     1091
#define IDC_FEMGEN3                     1092
#define IDC_FEMGEN4                     1093
#define IDC_FEMGEN5                     1094
#define IDC_FEMGEN6                     1095
#define IDC_MALEGEN1                    1096
#define IDC_MALEGEN2                    1097
#define IDC_MALEGEN3                    1098
#define IDC_MALEGEN4                    1099
#define IDC_MALEGEN5                    1100
#define IDC_MALEGEN6                    1101
#define IDC_MALEGEN7                    1102
#define IDC_FHAIR1                      1103
#define IDC_FHAIR2                      1104
#define IDC_FHAIR3                      1105
#define IDC_FHAIR4                      1106
#define IDC_FHAIR5                      1107
#define IDC_FHAIR6                      1108
#define IDC_CHEST1                      1109
#define IDC_CHEST2                      1110
#define IDC_CHEST3                      1111
#define IDC_CHEST4                      1112
#define IDC_CHEST5                      1113
#define IDC_BUILD1                      1114
#define IDC_BUILD2                      1115
#define IDC_BUILD3                      1116
#define IDC_BUILD4                      1117
#define IDC_BUILD5                      1118
#define IDC_BUILD6                      1119
#define IDC_BUILD7                      1120
#define IDC_RACE1                       1121
#define IDC_RACE2                       1122
#define IDC_RACE3                       1123
#define IDC_RACE4                       1124
#define IDC_RACE5                       1125
#define IDC_RACE6                       1126
#define IDC_AGE1                        1127
#define IDC_AGE2                        1128
#define IDC_AGE3                        1129
#define IDC_AGE4                        1130
#define IDC_AGE5                        1131
#define IDC_AGE6                        1132
#define IDC_AGE7                        1133
#define IDC_AGE8                        1134
#define IDC_HEIGHT1                     1135
#define IDC_HEIGHT2                     1136
#define IDC_HEIGHT3                     1137
#define IDC_HCOLOR1                     1138
#define IDC_HCOLOR2                     1139
#define IDC_HCOLOR3                     1140
#define IDC_HCOLOR4                     1141
#define IDC_HCOLOR5                     1142
#define IDC_HCOLOR6                     1143
#define IDC_HSTYLE1                     1144
#define IDC_HSTYLE2                     1145
#define IDC_HSTYLE3                     1146
#define IDC_HSTYLE4                     1147
#define IDC_HSTYLE5                     1148
#define IDC_HSTYLE6                     1149
#define IDC_SKIN1                       1150
#define IDC_SKIN2                       1151
#define IDC_SKIN3                       1152
#define IDC_SKIN5                       1153
#define IDC_SKIN6                       1154
#define IDC_BUTT1                       1155
#define IDC_BUTT2                       1156
#define IDC_EYES1                       1157
#define IDC_EYES2                       1158
#define IDC_EYES3                       1159
#define IDC_EYES4                       1160
#define IDC_EYES5                       1161
#define IDC_MAXWIDTH                    1162
#define IDC_MAXHEIGHT                   1163
#define IDC_MAXSIZE                     1164
#define IDC_QUERY                       1165
#define IDC_FILTER                      1166
#define IDC_QUERYHELP                   1167
#define IDC_PREVIEW                     1168
#define IDC_RUNQUERY                    1182
#define IDC_RESULTS                     1183
#define IDC_HOSTS                       1184
#define IDC_GETFILE                     1185
#define IDC_GETTHUMB                    1186
#define IDC_PWDPROTECT                  1186
#define IDC_CHANGEPWD                   1187
#define IDC_AUTOLOGIN                   1188
#define IDC_SAVESEARCHES                1189
#define IDC_SPEED                       1190
#define IDC_TRANSFER_AUTO               1191
#define IDC_TRANSFER_MANUAL             1192
#define IDC_MAXTHUMBS                   1193
#define IDC_SAVEDFILES                  1194
#define IDC_CHOOSE                      1195
#define IDC_MAXPICTURES                 1196
#define IDC_UPLOAD_ENABLE               1196
#define IDC_SHARE_SAVED                 1197
#define IDC_SHARE_CUSTOM                1198
#define IDC_UPLOAD_DISABLE              1199
#define IDC_SHAREDFILES                 1200
#define IDC_MAXUPLOADS                  1201
#define IDC_ENABLE                      1202
#define IDC_CONFIG_CHOOSE               1203
#define IDC_EDIT                        1204
#define IDC_RESET                       1205
#define IDC_STATIC_USERNAME             1205
#define IDC_DB_CHOOSE                   1206
#define IDC_STATIC_PASSWORD             1206
#define IDC_DELETE                      1207
#define IDC_STATIC_MAXTHUMBS            1207
#define IDC_STATIC_MAXPICTURES          1208
#define IDC_STATIC_UPLOADS              1209
#define IDC_STATIC_SHARED               1210
#define IDC_STATIC_MAXUPLOADS           1211
#define IDC_STATIC_SHARED2              1212
#define IDC_LIST1                       1213
#define ID_DETAILS                      1214
#define IDC_DETAILS                     1215
#define IDC_PWD                         1216
#define IDC_VERSION                     1218
#define IDC_WEB                         1219
#define IDC_NAME                        1223
#define IDC_IMAGESIZE                   1224
#define IDC_SIGNUP                      1225
#define IDC_PROGRESS                    1226
#define IDC_RATE                        1227
#define IDC_RECONNECT                   1229
#define IDC_RECONNCT_DELAY              1230
#define IDC_STATIC_RECONNECT1           1231
#define IDC_STATIC_RECONNECT2           1232
#define ID_ZOOMIN                       32778
#define ID_ZOOMOUT                      32779
#define ID_DOWNLOAD                     32781
#define ID_FIELDS_NEXT                  32782
#define ID_FIELDS_WAIT                  32783
#define ID_FIELDS_1                     32784
#define ID_FIELDS_2                     32785
#define ID_FIELDS_3                     32786
#define ID_FIELDS_4                     32787
#define ID_FIELDS_5                     32788
#define ID_FIELDS_6                     32789
#define ID_FIELDS_7                     32790
#define ID_FIELDS_8                     32791
#define ID_OPTIONS                      32792
#define ID_INDEXER                      32793
#define ID_CONNECT                      32794
#define ID_DISCONNECT                   32795
#define ID_SHARED                       32796
#define ID_ABOUT                        32798
#define ID_EXIT                         32799
#define ID_UNSHAREFILE                  32800
#define ID_INDEXFILE                    32801
#define ID_SHAREFILE                    32802
#define ID_TRAY_SHOW                    32803
#define ID_TRAY_OPTIONS                 32805
#define ID_FIT                          32806

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        184
#define _APS_NEXT_COMMAND_VALUE         32807
#define _APS_NEXT_CONTROL_VALUE         1233
#define _APS_NEXT_SYMED_VALUE           129
#endif
#endif
