[InstallShield Silent]
Version=v5.00.000
File=Response File

[DlgOrder]
Dlg0=SdWelcome-0
Count=5
Dlg1=SdLicense-0
Dlg2=ServerConnect-0
Dlg3=SdStartCopy-0
Dlg4=SdFinish-0

[SdWelcome-0]
Result=1

[SdLicense-0]
Result=1

[ServerConnect-0]
NTAuthentication=0
SQLAuthentication=1
svPassword=.
Result=1

[SdStartCopy-0]
Result=1

[Application]
Name=Service Pack 2
Version=7.00.00
Company=Microsoft
Lang=0009

[SdFinish-0]
Result=1
bOpt1=0
bOpt2=0
